#!/usr/bin/env sage

"""
Find EXACT formula for new(m) = am² + bm + c

Known data:
- m=2: new=6
- m=8: new=20
- m=28: new=156
- m=184: new=1460
- m=1644: new=17424

User's insight: correction/m² → 3, which suggests new(m) → 3m²/2 - 3m/2
This means we expect: a ≈ 1.5, b ≈ -1.5, c ≈ 0

Solve exactly using first 3 data points.
"""


# This file was *autogenerated* from the file exact_formula_solution.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_6 = Integer(6); _sage_const_8 = Integer(8); _sage_const_20 = Integer(20); _sage_const_28 = Integer(28); _sage_const_156 = Integer(156); _sage_const_184 = Integer(184); _sage_const_1460 = Integer(1460); _sage_const_1644 = Integer(1644); _sage_const_17424 = Integer(17424); _sage_const_70 = Integer(70); _sage_const_4 = Integer(4); _sage_const_1 = Integer(1); _sage_const_64 = Integer(64); _sage_const_784 = Integer(784); _sage_const_0p0001 = RealNumber('0.0001'); _sage_const_17 = Integer(17); _sage_const_5 = Integer(5); _sage_const_19068 = Integer(19068); _sage_const_0p5 = RealNumber('0.5'); _sage_const_16 = Integer(16); _sage_const_0 = Integer(0); _sage_const_11 = Integer(11); _sage_const_3 = Integer(3)
from sage.all import *

# Known data
data = [
    (_sage_const_2 , _sage_const_6 ),
    (_sage_const_8 , _sage_const_20 ),
    (_sage_const_28 , _sage_const_156 ),
    (_sage_const_184 , _sage_const_1460 ),
    (_sage_const_1644 , _sage_const_17424 ),
]

print("="*_sage_const_70 )
print("EXACT FORMULA SOLUTION: new(m) = am² + bm + c")
print("="*_sage_const_70 )
print()

# System of equations using first 3 points:
# 4a + 2b + c = 6     (m=2)
# 64a + 8b + c = 20   (m=8)
# 784a + 28b + c = 156 (m=28)

print("Setting up system of equations:")
print("  4a + 2b + c = 6")
print("  64a + 8b + c = 20")
print("  784a + 28b + c = 156")
print()

# Solve using Sage's linear algebra
from sage.all import matrix, vector

# Coefficient matrix
A = matrix(QQ, [
    [_sage_const_4 , _sage_const_2 , _sage_const_1 ],
    [_sage_const_64 , _sage_const_8 , _sage_const_1 ],
    [_sage_const_784 , _sage_const_28 , _sage_const_1 ]
])

# Right-hand side
b_vec = vector(QQ, [_sage_const_6 , _sage_const_20 , _sage_const_156 ])

# Solve Ax = b
solution = A.solve_right(b_vec)
a, b, c = solution

print("EXACT SOLUTION:")
print(f"  a = {a}")
print(f"  b = {b}")
print(f"  c = {c}")
print()
print(f"Formula: new(m) = {a}·m² + {b}·m + {c}")
print()

# Verify on ALL data points
print("="*_sage_const_70 )
print("VERIFICATION ON ALL DATA POINTS")
print("="*_sage_const_70 )
print()
print("m     | Predicted           | Actual  | Error")
print("------|---------------------|---------|-------")

all_perfect = True
for m_val, new_actual in data:
    new_predicted = a * m_val**_sage_const_2  + b * m_val + c
    error = abs(float(new_predicted - new_actual))
    status = "✓" if error < _sage_const_0p0001  else "✗"
    if error >= _sage_const_0p0001 :
        all_perfect = False
    print(f"{m_val:5d} | {new_predicted:19} | {new_actual:7d} | {error:6.4f} {status}")

print()

if all_perfect:
    print("✓✓✓ PERFECT FIT on all 5 data points!")
else:
    print("✗ Formula does NOT fit all data perfectly")
    print("  This suggests new(m) is NOT a simple quadratic")

print()
print("="*_sage_const_70 )
print("EXTRAPOLATING TO g(16)")
print("="*_sage_const_70 )
print()

# Iterate recurrence: g(n+1) = g(n) + new(g(n))
g_current = _sage_const_2   # g(0) = 2
g_sequence = [g_current]

print(f"g(0) = {g_current}")

for day in range(_sage_const_1 , _sage_const_17 ):
    m_start = g_current
    new_points = a * m_start**_sage_const_2  + b * m_start + c
    g_current = g_current + new_points
    g_sequence.append(g_current)

    # Check for known values
    if day <= _sage_const_5 :
        expected = [_sage_const_2 , _sage_const_8 , _sage_const_28 , _sage_const_184 , _sage_const_1644 , _sage_const_19068 ][day]
        match = "✓" if abs(g_current - expected) < _sage_const_0p5  else "✗"
        print(f"g({day:2d}) = {int(g_current):20,} (expected {expected:8,}) {match}")
    else:
        print(f"g({day:2d}) = {int(g_current):20,}")

print()
print("="*_sage_const_70 )
print(f"ANSWER: g(16) = {int(g_sequence[_sage_const_16 ]):,}")
print("="*_sage_const_70 )
print()

# Sanity checks
print("Sanity checks:")
if g_sequence[_sage_const_16 ] > _sage_const_0 :
    print(f"  ✓ Result is positive: {int(g_sequence[_sage_const_16 ]):,}")
else:
    print(f"  ✗ Result is negative: INVALID")

if g_sequence[_sage_const_16 ] > g_sequence[_sage_const_5 ]:
    print(f"  ✓ g(16) > g(5): {int(g_sequence[_sage_const_16 ]):,} > {g_sequence[_sage_const_5 ]:,}")
else:
    print(f"  ✗ g(16) ≤ g(5): INVALID")

# Growth rate
growth_rate = (g_sequence[_sage_const_16 ] / g_sequence[_sage_const_5 ]) ** (_sage_const_1 /_sage_const_11 )
print(f"  ✓ Average growth rate g(5)→g(16): {float(growth_rate):.3f}× per day")

# Check if growth is monotonic
monotonic = all(g_sequence[i+_sage_const_1 ] > g_sequence[i] for i in range(_sage_const_16 ))
if monotonic:
    print(f"  ✓ Sequence is monotonically increasing")
else:
    print(f"  ✗ Sequence is NOT monotonic: INVALID")

print()
print("="*_sage_const_70 )
print("FORMULA INTERPRETATION")
print("="*_sage_const_70 )
print()

if a == QQ(_sage_const_3 )/QQ(_sage_const_2 ) and b == QQ(-_sage_const_3 )/QQ(_sage_const_2 ) and c == _sage_const_0 :
    print("✓ Formula matches user's asymptotic prediction!")
    print(f"  new(m) = (3/2)m² - (3/2)m")
    print(f"  new(m) = (3/2)m(m - 1)")
    print(f"  new(m) = (3/2) × C(m, 2) × 2")
    print(f"  new(m) = 3 × C(m, 2)")
    print()
    print("This is ELEGANT: new points = 3 times the binomial coefficient C(m,2)")
elif c == _sage_const_0 :
    print("Formula has no constant term (c=0)")
    print(f"  new(m) = {a}m² + {b}m = m({a}m + {b})")
else:
    print(f"Formula: new(m) = {a}m² + {b}m + {c}")

print()
print("="*_sage_const_70 )

