#!/usr/bin/env sage

"""
Find EXACT formula for new(m) = am² + bm + c

Known data:
- m=2: new=6
- m=8: new=20
- m=28: new=156
- m=184: new=1460
- m=1644: new=17424

User's prediction: a ≈ 1.5 (=3/2), b ≈ -1.5 (=-3/2), c ≈ 0
"""


# This file was *autogenerated* from the file exact_formula_solution_v2.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_6 = Integer(6); _sage_const_8 = Integer(8); _sage_const_20 = Integer(20); _sage_const_28 = Integer(28); _sage_const_156 = Integer(156); _sage_const_184 = Integer(184); _sage_const_1460 = Integer(1460); _sage_const_1644 = Integer(1644); _sage_const_17424 = Integer(17424); _sage_const_70 = Integer(70); _sage_const_4 = Integer(4); _sage_const_1 = Integer(1); _sage_const_64 = Integer(64); _sage_const_784 = Integer(784); _sage_const_3 = Integer(3); _sage_const_0 = Integer(0); _sage_const_0p0001 = RealNumber('0.0001'); _sage_const_1p5 = RealNumber('1.5'); _sage_const_0p001 = RealNumber('0.001'); _sage_const_17 = Integer(17); _sage_const_5 = Integer(5); _sage_const_19068 = Integer(19068); _sage_const_0p5 = RealNumber('0.5'); _sage_const_16 = Integer(16); _sage_const_11 = Integer(11)
from sage.all import *

# Known data
data = [
    (_sage_const_2 , _sage_const_6 ),
    (_sage_const_8 , _sage_const_20 ),
    (_sage_const_28 , _sage_const_156 ),
    (_sage_const_184 , _sage_const_1460 ),
    (_sage_const_1644 , _sage_const_17424 ),
]

print("="*_sage_const_70 )
print("EXACT FORMULA SOLUTION: new(m) = am² + bm + c")
print("="*_sage_const_70 )
print()

# System of equations using first 3 points:
# 4a + 2b + c = 6     (m=2)
# 64a + 8b + c = 20   (m=8)
# 784a + 28b + c = 156 (m=28)

print("Setting up system of equations using first 3 data points:")
print("  4a + 2b + c = 6")
print("  64a + 8b + c = 20")
print("  784a + 28b + c = 156")
print()

# Solve using Sage's linear algebra
A = matrix(QQ, [
    [_sage_const_4 , _sage_const_2 , _sage_const_1 ],
    [_sage_const_64 , _sage_const_8 , _sage_const_1 ],
    [_sage_const_784 , _sage_const_28 , _sage_const_1 ]
])

b_vec = vector(QQ, [_sage_const_6 , _sage_const_20 , _sage_const_156 ])
solution = A.solve_right(b_vec)
a, b, c = solution

print("EXACT SOLUTION:")
print("  a = %s = %.10f" % (a, float(a)))
print("  b = %s = %.10f" % (b, float(b)))
print("  c = %s = %.10f" % (c, float(c)))
print()
print("Formula: new(m) = (%s)m² + (%s)m + (%s)" % (a, b, c))
print()

# Check if this matches 3/2, -3/2, 0
expected_a = QQ(_sage_const_3 )/QQ(_sage_const_2 )
expected_b = QQ(-_sage_const_3 )/QQ(_sage_const_2 )
expected_c = QQ(_sage_const_0 )

if a == expected_a and b == expected_b and c == expected_c:
    print("✓✓✓ MATCHES USER'S PREDICTION: new(m) = (3/2)m² - (3/2)m")
    print("    Simplifies to: new(m) = (3/2)m(m-1) = 3·C(m,2)")
else:
    print("✗ Does NOT match user's prediction (3/2, -3/2, 0)")
    print("  Got: (%s, %s, %s)" % (a, b, c))

print()
print("="*_sage_const_70 )
print("VERIFICATION ON ALL DATA POINTS")
print("="*_sage_const_70 )
print()
print("m     | Predicted | Actual  | Error")
print("------|-----------|---------|--------")

max_error = _sage_const_0 
for m_val, new_actual in data:
    new_predicted = a * m_val**_sage_const_2  + b * m_val + c
    error = abs(float(new_predicted - new_actual))
    max_error = max(max_error, error)
    status = "✓" if error < _sage_const_0p0001  else "✗"
    print("%5d | %9.2f | %7d | %6.4f %s" % (m_val, float(new_predicted), new_actual, error, status))

print()
if max_error < _sage_const_0p0001 :
    print("✓✓✓ PERFECT FIT on all 5 data points!")
else:
    print("✗ Formula does NOT fit perfectly (max error: %.4f)" % max_error)
    print("  This suggests new(m) is NOT a simple quadratic")

print()
print("="*_sage_const_70 )
print("TRYING ALTERNATIVE APPROACH: Use ALL 5 points for overdetermined system")
print("="*_sage_const_70 )
print()

# Try least-squares fit using all 5 points
A_full = matrix(QQ, [[m**_sage_const_2 , m, _sage_const_1 ] for m, _ in data])
b_full = vector(QQ, [new for _, new in data])

# Least squares: (A^T A)x = A^T b
ATA = A_full.transpose() * A_full
ATb = A_full.transpose() * b_full
solution_ls = ATA.solve_right(ATb)
a_ls, b_ls, c_ls = solution_ls

print("Least-squares solution using ALL 5 points:")
print("  a = %s = %.10f" % (a_ls, float(a_ls)))
print("  b = %s = %.10f" % (b_ls, float(b_ls)))
print("  c = %s = %.10f" % (c_ls, float(c_ls)))
print()

# Check for 3/2, -3/2, 0
if abs(float(a_ls) - _sage_const_1p5 ) < _sage_const_0p001  and abs(float(b_ls) + _sage_const_1p5 ) < _sage_const_0p001  and abs(float(c_ls)) < _sage_const_0p001 :
    print("✓✓✓ CLOSE TO (3/2, -3/2, 0)!")
    print("    Testing exact formula: new(m) = (3/2)m² - (3/2)m")
    a_test = QQ(_sage_const_3 )/QQ(_sage_const_2 )
    b_test = QQ(-_sage_const_3 )/QQ(_sage_const_2 )
    c_test = QQ(_sage_const_0 )

    print()
    print("Testing new(m) = (3/2)m(m-1):")
    print("m     | Predicted | Actual  | Error")
    print("------|-----------|---------|--------")

    for m_val, new_actual in data:
        new_predicted = a_test * m_val**_sage_const_2  + b_test * m_val + c_test
        error = abs(float(new_predicted - new_actual))
        status = "✓" if error < _sage_const_0p0001  else "✗"
        print("%5d | %9.2f | %7d | %6.4f %s" % (m_val, float(new_predicted), new_actual, error, status))

print()
print("="*_sage_const_70 )
print("EXTRAPOLATING TO g(16) using least-squares coefficients")
print("="*_sage_const_70 )
print()

# Use the least-squares solution
a_final = a_ls
b_final = b_ls
c_final = c_ls

g_current = _sage_const_2   # g(0) = 2
g_sequence = [g_current]

print("g(0) = %d" % g_current)

for day in range(_sage_const_1 , _sage_const_17 ):
    m_start = g_current
    new_points = a_final * m_start**_sage_const_2  + b_final * m_start + c_final
    g_current = g_current + new_points
    g_sequence.append(g_current)

    if day <= _sage_const_5 :
        expected = [_sage_const_2 , _sage_const_8 , _sage_const_28 , _sage_const_184 , _sage_const_1644 , _sage_const_19068 ][day]
        error = abs(float(g_current - expected))
        match = "✓" if error < _sage_const_0p5  else "✗"
        print("g(%2d) = %20s (expected %8d, error %.2f) %s" % (day, str(int(g_current)), expected, error, match))
    else:
        print("g(%2d) = %20s" % (day, str(int(g_current))))

print()
print("="*_sage_const_70 )
print("ANSWER: g(16) = %s" % str(int(g_sequence[_sage_const_16 ])))
print("="*_sage_const_70 )
print()

# Sanity checks
print("Sanity checks:")
if g_sequence[_sage_const_16 ] > _sage_const_0 :
    print("  ✓ Result is positive: %s" % str(int(g_sequence[_sage_const_16 ])))
else:
    print("  ✗ Result is negative: INVALID")

if g_sequence[_sage_const_16 ] > g_sequence[_sage_const_5 ]:
    print("  ✓ g(16) > g(5)")
else:
    print("  ✗ g(16) ≤ g(5): INVALID")

growth_rate = (g_sequence[_sage_const_16 ] / g_sequence[_sage_const_5 ]) ** (QQ(_sage_const_1 )/QQ(_sage_const_11 ))
print("  Average growth rate g(5)→g(16): %.3f× per day" % float(growth_rate))

monotonic = all(g_sequence[i+_sage_const_1 ] > g_sequence[i] for i in range(_sage_const_16 ))
if monotonic:
    print("  ✓ Sequence is monotonically increasing")
else:
    print("  ✗ Sequence is NOT monotonic: INVALID")

print()
print("="*_sage_const_70 )

