#!/usr/bin/env sage

"""
RECURRENCE APPROACH - Problem 957

KEY INSIGHT: Fit polynomial to GROWTH FUNCTION, not sequence.

Given data:
- new(2) = 6  (since g(1) = g(0) + new(g(0)) = 2 + 6 = 8)
- new(8) = 20 (since g(2) = g(1) + new(g(1)) = 8 + 20 = 28)
- new(28) = 156
- new(184) = 1460
- new(1644) = 17424

Find: new(m) = am² + bm + c

Then iterate: m_{n+1} = m_n + new(m_n)
"""


# This file was *autogenerated* from the file recurrence_formula_solution.sage
from sage.all_cmdline import *   # import sage library

_sage_const_70 = Integer(70); _sage_const_2 = Integer(2); _sage_const_6 = Integer(6); _sage_const_8 = Integer(8); _sage_const_20 = Integer(20); _sage_const_28 = Integer(28); _sage_const_156 = Integer(156); _sage_const_184 = Integer(184); _sage_const_1460 = Integer(1460); _sage_const_1644 = Integer(1644); _sage_const_17424 = Integer(17424); _sage_const_4 = Integer(4); _sage_const_1 = Integer(1); _sage_const_64 = Integer(64); _sage_const_784 = Integer(784); _sage_const_1p5 = RealNumber('1.5'); _sage_const_0p01 = RealNumber('0.01'); _sage_const_0 = Integer(0); _sage_const_100 = Integer(100); _sage_const_10 = Integer(10); _sage_const_19068 = Integer(19068); _sage_const_17 = Integer(17); _sage_const_5 = Integer(5); _sage_const_16 = Integer(16); _sage_const_15 = Integer(15)
from sage.all import *

print("="*_sage_const_70 )
print("RECURRENCE FORMULA APPROACH")
print("="*_sage_const_70 )
print()

# Growth function data: (m, new_points_added)
growth_data = [
    (_sage_const_2 , _sage_const_6 ),
    (_sage_const_8 , _sage_const_20 ),
    (_sage_const_28 , _sage_const_156 ),
    (_sage_const_184 , _sage_const_1460 ),
    (_sage_const_1644 , _sage_const_17424 ),
]

print("Growth function data: new(m) = number of points added when starting with m blues")
print()
for m, new in growth_data:
    print(f"  new({m:4d}) = {new:6d}")
print()

# Use first 3 points to solve for exact quadratic coefficients
print("="*_sage_const_70 )
print("SOLVING FOR EXACT QUADRATIC: new(m) = am² + bm + c")
print("="*_sage_const_70 )
print()

# System of equations using first 3 points
# new(2) = 4a + 2b + c = 6
# new(8) = 64a + 8b + c = 20
# new(28) = 784a + 28b + c = 156

A = matrix(QQ, [
    [_sage_const_4 , _sage_const_2 , _sage_const_1 ],
    [_sage_const_64 , _sage_const_8 , _sage_const_1 ],
    [_sage_const_784 , _sage_const_28 , _sage_const_1 ]
])

b_vec = vector(QQ, [_sage_const_6 , _sage_const_20 , _sage_const_156 ])
solution = A.solve_right(b_vec)
a, b, c = solution

print(f"Exact solution from first 3 points:")
print(f"  a = {a} = {float(a):.10f}")
print(f"  b = {b} = {float(b):.10f}")
print(f"  c = {c} = {float(c):.10f}")
print()
print(f"Formula: new(m) = ({a})m² + ({b})m + ({c})")
print()

# Check if this is close to 3/2, -3/2, 0
if abs(float(a) - _sage_const_1p5 ) < _sage_const_0p01 :
    print("✓ Coefficient a ≈ 3/2 (user's prediction)")
if abs(float(b) + _sage_const_1p5 ) < _sage_const_0p01 :
    print("✓ Coefficient b ≈ -3/2 (user's prediction)")
if abs(float(c)) < _sage_const_0p01 :
    print("✓ Coefficient c ≈ 0 (user's prediction)")
print()

# Verify on ALL growth data points
print("="*_sage_const_70 )
print("VERIFICATION ON ALL GROWTH DATA")
print("="*_sage_const_70 )
print()
print("m     | Predicted  | Actual  | Error    | Status")
print("------|------------|---------|----------|-------")

max_error = _sage_const_0 
for m, new_actual in growth_data:
    new_predicted = a * m**_sage_const_2  + b * m + c
    error = abs(float(new_predicted - new_actual))
    pct_error = _sage_const_100  * error / new_actual if new_actual > _sage_const_0  else _sage_const_0 
    status = "✓" if pct_error < _sage_const_1  else "✗"
    max_error = max(max_error, pct_error)
    print(f"{m:5d} | {float(new_predicted):10.2f} | {new_actual:7d} | {error:8.2f} | {status} ({pct_error:5.2f}%)")

print()
if max_error < _sage_const_1 :
    print(f"✓ Excellent fit (max error: {max_error:.2f}%)")
elif max_error < _sage_const_10 :
    print(f"⚠ Acceptable fit (max error: {max_error:.2f}%)")
else:
    print(f"✗ Poor fit (max error: {max_error:.2f}%) - formula may be incorrect")
print()

# ITERATE THE RECURRENCE
print("="*_sage_const_70 )
print("ITERATING RECURRENCE: m_{n+1} = m_n + new(m_n)")
print("="*_sage_const_70 )
print()

# Start with m_0 = 2 (g(0) = 2)
m_current = Integer(_sage_const_2 )
g_sequence = [m_current]

print(f"g(0) = {m_current}")

# Known values for verification
known_values = [_sage_const_2 , _sage_const_8 , _sage_const_28 , _sage_const_184 , _sage_const_1644 , _sage_const_19068 ]

for day in range(_sage_const_1 , _sage_const_17 ):
    # Compute new points using formula
    new_points = a * m_current**_sage_const_2  + b * m_current + c

    # Round to nearest integer (formula may not be exact)
    new_points_int = Integer(round(new_points))

    # Update
    m_current = m_current + new_points_int
    g_sequence.append(m_current)

    # Display with verification for known values
    if day <= _sage_const_5 :
        expected = known_values[day]
        error = abs(m_current - expected)
        match = "✓" if error == _sage_const_0  else "✗"
        print(f"g({day:2d}) = {m_current:20,} (expected {expected:8,}) {match}")
    else:
        print(f"g({day:2d}) = {m_current:20,}")

print()
print("="*_sage_const_70 )
print(f"ANSWER: g(16) = {g_sequence[_sage_const_16 ]:,}")
print("="*_sage_const_70 )
print()

# Sanity checks
print("Sanity checks:")
if g_sequence[_sage_const_16 ] > _sage_const_0 :
    print(f"  ✓ Result is positive: {g_sequence[_sage_const_16 ]:,}")
else:
    print(f"  ✗ Result is negative: INVALID")

if all(g_sequence[i+_sage_const_1 ] > g_sequence[i] for i in range(_sage_const_16 )):
    print(f"  ✓ Sequence is monotonically increasing")
else:
    print(f"  ✗ Sequence NOT monotonic: INVALID")

if g_sequence[_sage_const_16 ] > g_sequence[_sage_const_5 ]:
    print(f"  ✓ g(16) > g(5): {g_sequence[_sage_const_16 ]:,} > {g_sequence[_sage_const_5 ]:,}")

# Check if result is reasonable (< 10^15 per PE convention)
if g_sequence[_sage_const_16 ] < _sage_const_10 **_sage_const_15 :
    print(f"  ✓ Result is reasonable PE size (< 10^15)")
else:
    print(f"  ✗ Result is too large: LIKELY INVALID")

print()
print("Growth rate analysis:")
for i in range(min(_sage_const_6 , len(g_sequence)-_sage_const_1 )):
    rate = float(g_sequence[i+_sage_const_1 ]) / float(g_sequence[i])
    print(f"  g({i+_sage_const_1 })/g({i}) = {rate:.6f}")

print()
print("="*_sage_const_70 )

