

# This file was *autogenerated* from the file practice.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4)# Lesson 2.3 Subsets (Power Set)

S = Subsets([_sage_const_1 , _sage_const_2 , _sage_const_3 ])
print("All subsets:")
for subset in S:
    print(subset)
print("Total:", S.cardinality())

# Filter: only subsets of size 2

S2 = Subsets([_sage_const_1 , _sage_const_2 , _sage_const_3 , _sage_const_4 ], _sage_const_2 )
print("\nSubsets of size 2:")
print(list(S2))

# Expected: 2^3 = 8 subsets (includes empty set), then 6 size-2 subsets.

