#!/bin/bash
echo "Language|Solution Lines|Test Lines|Solution File|Test File"
echo "C|$(wc -l < c/matrix_product.c)|$(wc -l < c/test_matrix_product.c)|c/matrix_product.c|c/test_matrix_product.c"
echo "C++|$(wc -l < cpp/matrix_product.cpp)|$(wc -l < cpp/test_matrix_product.cpp)|cpp/matrix_product.cpp|cpp/test_matrix_product.cpp"
echo "C#|$(wc -l < csharp/MatrixProduct.cs)|$(wc -l < csharp/MatrixProductTest.cs)|csharp/MatrixProduct.cs|csharp/MatrixProductTest.cs"
echo "Fortran|$(wc -l < fortran/matrix_product.f90)|$(wc -l < fortran/matrix_product_test.f90)|fortran/matrix_product.f90|fortran/matrix_product_test.f90"
echo "Go|$(wc -l < go/matrix_product.go)|$(wc -l < go/matrix_product_test.go)|go/matrix_product.go|go/matrix_product_test.go"
echo "Haskell|$(wc -l < haskell/app/Main.hs)|$(wc -l < haskell/src/MatrixProductTest.hs)|haskell/app/Main.hs|haskell/src/MatrixProductTest.hs"
echo "Java|$(wc -l < java/MatrixProduct.java)|$(wc -l < java/MatrixProductTest.java)|java/MatrixProduct.java|java/MatrixProductTest.java"
echo "Julia|$(wc -l < julia/matrix_product.jl)|$(wc -l < julia/matrix_product_test.jl)|julia/matrix_product.jl|julia/matrix_product_test.jl"
echo "Kotlin|$(wc -l < kotlin/src/main/kotlin/MatrixProduct.kt)|$(wc -l < kotlin/src/test/kotlin/MatrixProductTest.kt)|kotlin/src/main/kotlin/MatrixProduct.kt|kotlin/src/test/kotlin/MatrixProductTest.kt"
echo "Perl|$(wc -l < perl/matrix_product.pl)|$(wc -l < perl/matrix_product_test.pl 2>/dev/null || echo 'N/A')|perl/matrix_product.pl|perl/matrix_product_test.pl"
echo "PHP|$(wc -l < php/solution.php)|$(wc -l < php/MatrixProductTest.php)|php/solution.php|php/MatrixProductTest.php"
echo "Python|$(wc -l < python/matrix_product.py)|$(wc -l < python/test_matrix_product.py)|python/matrix_product.py|python/test_matrix_product.py"
echo "Ruby|$(wc -l < ruby/matrix_product.rb)|$(wc -l < ruby/matrix_product_test.rb)|ruby/matrix_product.rb|ruby/matrix_product_test.rb"
echo "Rust|$(wc -l < rust/src/main.rs)|$(wc -l < rust/tests/greatest_product.rs)|rust/src/main.rs|rust/tests/greatest_product.rs"
echo "Scala|$(wc -l < scala/src/main/scala/MatrixProduct.scala)|$(wc -l < scala/src/test/scala/MatrixProductTest.scala)|scala/src/main/scala/MatrixProduct.scala|scala/src/test/scala/MatrixProductTest.scala"
echo "Swift|$(wc -l < swift/MatrixProduct.swift)|$(wc -l < swift/MatrixProductTests.swift)|swift/MatrixProduct.swift|swift/MatrixProductTests.swift"
echo "TypeScript|$(wc -l < typescript/matrixProduct.ts)|$(wc -l < typescript/matrixProduct.test.ts)|typescript/matrixProduct.ts|typescript/matrixProduct.test.ts"
