[package]
name = "problem12"
version = "0.1.0"
edition = "2024"

[dependencies]

[dev-dependencies]
rstest = "*"
speculate = "*"
proptest = "1.0"
criterion = "0.5"

[[bench]]
name = "performance_baseline"
harness = false
